library(plumber)
library(stars)
library(jsonlite)
library(raster)
library(base64enc)
library(zip)

udf_json = plumb("/opt/dockerfiles/R/json.R")
udf_binary = plumb("/opt/dockerfiles/R/binary.R")
udf = plumber$new()
udf$mount("/", udf_json)
udf$mount("/", udf_binary)
udf$run(host="0.0.0.0",port=8010)
