library(plumber)
library(stars)
library(jsonlite)
library(raster)
library(base64enc)
library(zip)

REST_UDFs = plumb("/opt/dockerfiles/R/RESTful_services.R")
# udf_binary = plumb("/opt/dockerfiles/R/binary.R")
REST_UDFs$run(host = "0.0.0.0", port = 8010)
